\connect proyecto
DROP TABLE Padecimiento_enfermedad_4;
DROP TABLE Padecimiento_alergia_4;
DROP TABLE Alergia_4;
DROP TABLE Enfermedad_4;
DROP TABLE Tratamiento_4;
DROP TABLE Medicamento_4;
DROP TABLE Sintoma_4;
DROP TABLE Gusto_4;
DROP TABLE Juego_4;
DROP TABLE Atencion_4;
DROP TABLE Pediatra_4;
DROP TABLE Parentesco_nino_4;
DROP TABLE Parentesco_Padre_4;
DROP TABLE menu_semanal_4;
DROP TABLE factura_menu_4;
DROP TABLE menu_4;
DROP TABLE comida_plato_4;
DROP TABLE comida_4;
DROP TABLE plato_4;
DROP TABLE multa_4;
DROP TABLE Asistencia_4;
DROP TABLE act_inscripcion_4;
DROP TABLE pago_mensual_4;
DROP TABLE inscripcion_4;
DROP TABLE autorizado_buscar_4;
DROP TABLE Nino_4;
DROP TABLE Horario_Act_Guarderia_4;
DROP TABLE Act_Guarderia_4;
DROP TABLE Actividad_4;
DROP TABLE Autorizado_4;
DROP TABLE Representante_4;
DROP TABLE Experiencia_4;
DROP TABLE Personal_4;
DROP TABLE Guarderia_4;
DROP TABLE Lugar_4;

\connect postgres
DROP DATABASE Proyecto;