/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GuarderiaController;
import Model.*;

/**
 *
 * @author Ignacio
 */
public class InitialView extends javax.swing.JFrame {
    
     private GuarderiaDAOImpl modeloGuarderia = new GuarderiaDAOImpl();
     private GuarderiaController controladorGuarderia = new GuarderiaController(this, modeloGuarderia);
     boolean comboBoxCreado = false;

    public InitialView() {
       initComponents();
       this.setTitle("Guarderías");
       this.setResizable(false);
       this.setLocationRelativeTo(null);
       controladorGuarderia.llenarComboBoxGuarderias(jComboGuarderias);
       controladorGuarderia.llenarComboBoxGuarderias(jComboGuarderias1);
       controladorGuarderia.llenarComboBoxGuarderias(jComboGuarderias2);
       controladorGuarderia.llenarComboBoxGuarderias(jComboGuarderias3);
       controladorGuarderia.llenarComboBoxGuarderias(jComboGuarderias4);
       controladorGuarderia.llenarComboBoxGuarderias(jComboGuarderias5);
       controladorGuarderia.llenarComboBoxGuarderias(jComboGuarderias6);
       controladorGuarderia.llenarComboBoxGuarderias(jComboGuarderias7);
       controladorGuarderia.llenarComboBoxGuarderias(jComboGuarderias8);
       controladorGuarderia.llenarComboBoxGuarderias(jComboGuarderias9);
       controladorGuarderia.llenarComboBoxGuarderias(jComboGuarderias10);
       comboBoxCreado = true;
       editGuarderiaButton.setEnabled(false);
       deleteGuarderiaButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelInicio = new javax.swing.JPanel();
        jComboGuarderias = new javax.swing.JComboBox<>();
        jPanelInfoGuarderia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rifLabel = new javax.swing.JLabel();
        casaLabel = new javax.swing.JLabel();
        calleLabel = new javax.swing.JLabel();
        municipioLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        ciudadLabel1 = new javax.swing.JLabel();
        horaEntradaLabel = new javax.swing.JLabel();
        horaSalidaLabel = new javax.swing.JLabel();
        addGuarderiaButton = new javax.swing.JButton();
        deleteGuarderiaButton = new javax.swing.JButton();
        editGuarderiaButton = new javax.swing.JButton();
        jPanelInscripcion = new javax.swing.JPanel();
        jComboGuarderias1 = new javax.swing.JComboBox<>();
        jPanelNinos = new javax.swing.JPanel();
        jComboGuarderias2 = new javax.swing.JComboBox<>();
        editGuarderiaButton1 = new javax.swing.JButton();
        jPanelInfoNino = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rifLabel1 = new javax.swing.JLabel();
        casaLabel1 = new javax.swing.JLabel();
        calleLabel1 = new javax.swing.JLabel();
        municipioLabel1 = new javax.swing.JLabel();
        estadoLabel1 = new javax.swing.JLabel();
        ciudadLabel2 = new javax.swing.JLabel();
        horaEntradaLabel1 = new javax.swing.JLabel();
        horaSalidaLabel1 = new javax.swing.JLabel();
        addGuarderiaButton1 = new javax.swing.JButton();
        deleteGuarderiaButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buscarNinoTextField = new javax.swing.JTextField();
        buscarNinoButton = new javax.swing.JButton();
        jPanelInfMedica = new javax.swing.JPanel();
        jComboGuarderias3 = new javax.swing.JComboBox<>();
        jPanelRepresentantes = new javax.swing.JPanel();
        jComboGuarderias4 = new javax.swing.JComboBox<>();
        jPanelNinos1 = new javax.swing.JPanel();
        jComboGuarderias11 = new javax.swing.JComboBox<>();
        editGuarderiaButton2 = new javax.swing.JButton();
        jPanelInfoNino1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rifLabel2 = new javax.swing.JLabel();
        casaLabel2 = new javax.swing.JLabel();
        calleLabel2 = new javax.swing.JLabel();
        municipioLabel2 = new javax.swing.JLabel();
        estadoLabel2 = new javax.swing.JLabel();
        ciudadLabel3 = new javax.swing.JLabel();
        horaEntradaLabel2 = new javax.swing.JLabel();
        horaSalidaLabel2 = new javax.swing.JLabel();
        addGuarderiaButton2 = new javax.swing.JButton();
        deleteGuarderiaButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRepresentantes = new javax.swing.JTable();
        buscarNinoTextField1 = new javax.swing.JTextField();
        buscarNinoButton1 = new javax.swing.JButton();
        jPanelPersonal = new javax.swing.JPanel();
        jComboGuarderias5 = new javax.swing.JComboBox<>();
        jPanelActividades = new javax.swing.JPanel();
        jComboGuarderias6 = new javax.swing.JComboBox<>();
        jPanelComida = new javax.swing.JPanel();
        jComboGuarderias7 = new javax.swing.JComboBox<>();
        jPanelPagos = new javax.swing.JPanel();
        jComboGuarderias8 = new javax.swing.JComboBox<>();
        jPanelMultas = new javax.swing.JPanel();
        jComboGuarderias9 = new javax.swing.JComboBox<>();
        jPanelTarifas = new javax.swing.JPanel();
        jComboGuarderias10 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboGuarderias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderiasActionPerformed(evt);
            }
        });

        jPanelInfoGuarderia.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de la Guardería"));

        jLabel1.setText("RIF:");

        jLabel2.setText("Dirección:");

        jLabel3.setText("Casa/Edificio:");

        jLabel4.setText("Calle/Av");

        jLabel6.setText("Municipio");

        jLabel7.setText("Ciudad");

        jLabel8.setText("Estado");

        jLabel9.setText("Hora de Entrada:");

        jLabel10.setText("Hora de Salida:");

        javax.swing.GroupLayout jPanelInfoGuarderiaLayout = new javax.swing.GroupLayout(jPanelInfoGuarderia);
        jPanelInfoGuarderia.setLayout(jPanelInfoGuarderiaLayout);
        jPanelInfoGuarderiaLayout.setHorizontalGroup(
            jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                .addGroup(jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rifLabel))
                            .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addComponent(horaEntradaLabel))
                            .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(horaSalidaLabel))))
                    .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calleLabel))
                            .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(casaLabel))
                            .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(municipioLabel))
                            .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ciudadLabel1))
                            .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(estadoLabel)))))
                .addGap(107, 107, 107))
        );
        jPanelInfoGuarderiaLayout.setVerticalGroup(
            jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoGuarderiaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rifLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(casaLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(calleLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(municipioLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ciudadLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(estadoLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(horaEntradaLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoGuarderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(horaSalidaLabel))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        addGuarderiaButton.setText("Agregar");
        addGuarderiaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addGuarderiaButtonMouseClicked(evt);
            }
        });

        deleteGuarderiaButton.setText("Eliminar");

        editGuarderiaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editGuarderiaButton.setToolTipText("");
        editGuarderiaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editGuarderiaButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addContainerGap(682, Short.MAX_VALUE)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                        .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboGuarderias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelInfoGuarderia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                                .addComponent(editGuarderiaButton)
                                .addGap(10, 10, 10)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInicioLayout.createSequentialGroup()
                        .addComponent(addGuarderiaButton)
                        .addGap(64, 64, 64)
                        .addComponent(deleteGuarderiaButton)
                        .addGap(57, 57, 57))))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboGuarderias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(editGuarderiaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInfoGuarderia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGuarderiaButton)
                    .addComponent(deleteGuarderiaButton))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inicio", jPanelInicio);

        jComboGuarderias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderias1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInscripcionLayout = new javax.swing.GroupLayout(jPanelInscripcion);
        jPanelInscripcion.setLayout(jPanelInscripcionLayout);
        jPanelInscripcionLayout.setHorizontalGroup(
            jPanelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInscripcionLayout.createSequentialGroup()
                .addContainerGap(761, Short.MAX_VALUE)
                .addComponent(jComboGuarderias1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelInscripcionLayout.setVerticalGroup(
            jPanelInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInscripcionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboGuarderias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inscripción", jPanelInscripcion);

        jComboGuarderias2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderias2ActionPerformed(evt);
            }
        });

        editGuarderiaButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editGuarderiaButton1.setToolTipText("");
        editGuarderiaButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editGuarderiaButton1MouseClicked(evt);
            }
        });

        jPanelInfoNino.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Niño"));

        jLabel5.setText("Nombre:");

        jLabel11.setText("Apellido:");

        jLabel12.setText("Sexo:");

        jLabel13.setText("Fecha de Nacimiento:");

        jLabel14.setText("Edad:");

        jLabel15.setText("Prentesco");

        javax.swing.GroupLayout jPanelInfoNinoLayout = new javax.swing.GroupLayout(jPanelInfoNino);
        jPanelInfoNino.setLayout(jPanelInfoNinoLayout);
        jPanelInfoNinoLayout.setHorizontalGroup(
            jPanelInfoNinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoNinoLayout.createSequentialGroup()
                .addGroup(jPanelInfoNinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoNinoLayout.createSequentialGroup()
                        .addGap(59, 131, Short.MAX_VALUE)
                        .addGroup(jPanelInfoNinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoNinoLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(26, 26, 26)
                                .addComponent(ciudadLabel2))
                            .addComponent(estadoLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoNinoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelInfoNinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horaEntradaLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(horaSalidaLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanelInfoNinoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelInfoNinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoNinoLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(municipioLabel1))
                            .addGroup(jPanelInfoNinoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(casaLabel1))
                            .addGroup(jPanelInfoNinoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelInfoNinoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rifLabel1))
                            .addGroup(jPanelInfoNinoLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calleLabel1)))))
                .addGap(107, 107, 107))
        );
        jPanelInfoNinoLayout.setVerticalGroup(
            jPanelInfoNinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoNinoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelInfoNinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(rifLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoNinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(casaLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoNinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(calleLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoNinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(municipioLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoNinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(ciudadLabel2))
                .addGap(18, 18, 18)
                .addComponent(estadoLabel1)
                .addGap(18, 18, 18)
                .addComponent(horaEntradaLabel1)
                .addGap(18, 18, 18)
                .addComponent(horaSalidaLabel1)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        addGuarderiaButton1.setText("Agregar");

        deleteGuarderiaButton1.setText("Eliminar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CI Representante", "Nombre", "Apellido", "Edad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buscarNinoButton.setText("Buscar");

        javax.swing.GroupLayout jPanelNinosLayout = new javax.swing.GroupLayout(jPanelNinos);
        jPanelNinos.setLayout(jPanelNinosLayout);
        jPanelNinosLayout.setHorizontalGroup(
            jPanelNinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNinosLayout.createSequentialGroup()
                .addGroup(jPanelNinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelNinosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addGuarderiaButton1)
                        .addGap(64, 64, 64)
                        .addComponent(deleteGuarderiaButton1)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNinosLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanelNinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNinosLayout.createSequentialGroup()
                                .addComponent(buscarNinoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarNinoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboGuarderias2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelNinosLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addGroup(jPanelNinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelInfoNino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNinosLayout.createSequentialGroup()
                                        .addComponent(editGuarderiaButton1)
                                        .addGap(10, 10, 10)))))))
                .addGap(24, 24, 24))
        );
        jPanelNinosLayout.setVerticalGroup(
            jPanelNinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNinosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelNinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboGuarderias2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarNinoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarNinoButton))
                .addGap(35, 35, 35)
                .addGroup(jPanelNinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNinosLayout.createSequentialGroup()
                        .addComponent(editGuarderiaButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelInfoNino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelNinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGuarderiaButton1)
                    .addComponent(deleteGuarderiaButton1))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Niños", jPanelNinos);

        jComboGuarderias3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderias3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfMedicaLayout = new javax.swing.GroupLayout(jPanelInfMedica);
        jPanelInfMedica.setLayout(jPanelInfMedicaLayout);
        jPanelInfMedicaLayout.setHorizontalGroup(
            jPanelInfMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfMedicaLayout.createSequentialGroup()
                .addContainerGap(761, Short.MAX_VALUE)
                .addComponent(jComboGuarderias3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelInfMedicaLayout.setVerticalGroup(
            jPanelInfMedicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfMedicaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboGuarderias3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inf. Médica", jPanelInfMedica);

        jComboGuarderias4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderias4ActionPerformed(evt);
            }
        });

        jComboGuarderias11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderias11ActionPerformed(evt);
            }
        });

        editGuarderiaButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        editGuarderiaButton2.setToolTipText("");
        editGuarderiaButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editGuarderiaButton2MouseClicked(evt);
            }
        });

        jPanelInfoNino1.setBorder(javax.swing.BorderFactory.createTitledBorder("Información del Padre"));

        jLabel16.setText("Nombre:");

        jLabel17.setText("Apellido:");

        jLabel18.setText("Sexo:");

        jLabel19.setText("Fecha de Nacimiento:");

        jLabel20.setText("Edad:");

        jLabel21.setText("Prentesco");

        javax.swing.GroupLayout jPanelInfoNino1Layout = new javax.swing.GroupLayout(jPanelInfoNino1);
        jPanelInfoNino1.setLayout(jPanelInfoNino1Layout);
        jPanelInfoNino1Layout.setHorizontalGroup(
            jPanelInfoNino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoNino1Layout.createSequentialGroup()
                .addGroup(jPanelInfoNino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoNino1Layout.createSequentialGroup()
                        .addGap(59, 131, Short.MAX_VALUE)
                        .addGroup(jPanelInfoNino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoNino1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(26, 26, 26)
                                .addComponent(ciudadLabel3))
                            .addComponent(estadoLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInfoNino1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelInfoNino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horaEntradaLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(horaSalidaLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanelInfoNino1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelInfoNino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInfoNino1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(municipioLabel2))
                            .addGroup(jPanelInfoNino1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(casaLabel2))
                            .addGroup(jPanelInfoNino1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelInfoNino1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rifLabel2))
                            .addGroup(jPanelInfoNino1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calleLabel2)))))
                .addGap(107, 107, 107))
        );
        jPanelInfoNino1Layout.setVerticalGroup(
            jPanelInfoNino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoNino1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelInfoNino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(rifLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoNino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(casaLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoNino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(calleLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoNino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(municipioLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoNino1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(ciudadLabel3))
                .addGap(18, 18, 18)
                .addComponent(estadoLabel2)
                .addGap(18, 18, 18)
                .addComponent(horaEntradaLabel2)
                .addGap(18, 18, 18)
                .addComponent(horaSalidaLabel2)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        addGuarderiaButton2.setText("Agregar");

        deleteGuarderiaButton2.setText("Eliminar");

        tablaRepresentantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CI", "Nombre", "Apellido", "Principal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaRepresentantes);

        buscarNinoButton1.setText("Buscar");

        javax.swing.GroupLayout jPanelNinos1Layout = new javax.swing.GroupLayout(jPanelNinos1);
        jPanelNinos1.setLayout(jPanelNinos1Layout);
        jPanelNinos1Layout.setHorizontalGroup(
            jPanelNinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNinos1Layout.createSequentialGroup()
                .addGroup(jPanelNinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelNinos1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addGuarderiaButton2)
                        .addGap(64, 64, 64)
                        .addComponent(deleteGuarderiaButton2)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNinos1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanelNinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNinos1Layout.createSequentialGroup()
                                .addComponent(buscarNinoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarNinoButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboGuarderias11, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelNinos1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addGroup(jPanelNinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelInfoNino1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNinos1Layout.createSequentialGroup()
                                        .addComponent(editGuarderiaButton2)
                                        .addGap(10, 10, 10)))))))
                .addGap(24, 24, 24))
        );
        jPanelNinos1Layout.setVerticalGroup(
            jPanelNinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNinos1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelNinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboGuarderias11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarNinoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarNinoButton1))
                .addGap(35, 35, 35)
                .addGroup(jPanelNinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNinos1Layout.createSequentialGroup()
                        .addComponent(editGuarderiaButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelInfoNino1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanelNinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGuarderiaButton2)
                    .addComponent(deleteGuarderiaButton2))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelRepresentantesLayout = new javax.swing.GroupLayout(jPanelRepresentantes);
        jPanelRepresentantes.setLayout(jPanelRepresentantesLayout);
        jPanelRepresentantesLayout.setHorizontalGroup(
            jPanelRepresentantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRepresentantesLayout.createSequentialGroup()
                .addContainerGap(761, Short.MAX_VALUE)
                .addComponent(jComboGuarderias4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanelRepresentantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRepresentantesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelNinos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelRepresentantesLayout.setVerticalGroup(
            jPanelRepresentantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRepresentantesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboGuarderias4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
            .addGroup(jPanelRepresentantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelRepresentantesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelNinos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Representantes", jPanelRepresentantes);

        jComboGuarderias5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderias5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPersonalLayout = new javax.swing.GroupLayout(jPanelPersonal);
        jPanelPersonal.setLayout(jPanelPersonalLayout);
        jPanelPersonalLayout.setHorizontalGroup(
            jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalLayout.createSequentialGroup()
                .addContainerGap(762, Short.MAX_VALUE)
                .addComponent(jComboGuarderias5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanelPersonalLayout.setVerticalGroup(
            jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jComboGuarderias5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(556, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personal", jPanelPersonal);

        jComboGuarderias6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderias6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelActividadesLayout = new javax.swing.GroupLayout(jPanelActividades);
        jPanelActividades.setLayout(jPanelActividadesLayout);
        jPanelActividadesLayout.setHorizontalGroup(
            jPanelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActividadesLayout.createSequentialGroup()
                .addContainerGap(761, Short.MAX_VALUE)
                .addComponent(jComboGuarderias6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelActividadesLayout.setVerticalGroup(
            jPanelActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActividadesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboGuarderias6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actividades", jPanelActividades);

        jComboGuarderias7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderias7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelComidaLayout = new javax.swing.GroupLayout(jPanelComida);
        jPanelComida.setLayout(jPanelComidaLayout);
        jPanelComidaLayout.setHorizontalGroup(
            jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComidaLayout.createSequentialGroup()
                .addContainerGap(761, Short.MAX_VALUE)
                .addComponent(jComboGuarderias7, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelComidaLayout.setVerticalGroup(
            jPanelComidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComidaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboGuarderias7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comida", jPanelComida);

        jComboGuarderias8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderias8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPagosLayout = new javax.swing.GroupLayout(jPanelPagos);
        jPanelPagos.setLayout(jPanelPagosLayout);
        jPanelPagosLayout.setHorizontalGroup(
            jPanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPagosLayout.createSequentialGroup()
                .addContainerGap(761, Short.MAX_VALUE)
                .addComponent(jComboGuarderias8, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelPagosLayout.setVerticalGroup(
            jPanelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboGuarderias8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pagos", jPanelPagos);

        jComboGuarderias9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderias9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMultasLayout = new javax.swing.GroupLayout(jPanelMultas);
        jPanelMultas.setLayout(jPanelMultasLayout);
        jPanelMultasLayout.setHorizontalGroup(
            jPanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMultasLayout.createSequentialGroup()
                .addContainerGap(761, Short.MAX_VALUE)
                .addComponent(jComboGuarderias9, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelMultasLayout.setVerticalGroup(
            jPanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMultasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboGuarderias9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Multas", jPanelMultas);

        jComboGuarderias10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGuarderias10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTarifasLayout = new javax.swing.GroupLayout(jPanelTarifas);
        jPanelTarifas.setLayout(jPanelTarifasLayout);
        jPanelTarifasLayout.setHorizontalGroup(
            jPanelTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTarifasLayout.createSequentialGroup()
                .addContainerGap(761, Short.MAX_VALUE)
                .addComponent(jComboGuarderias10, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanelTarifasLayout.setVerticalGroup(
            jPanelTarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTarifasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jComboGuarderias10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(562, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tarifas", jPanelTarifas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboGuarderiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderiasActionPerformed
        if (comboBoxCreado && !controladorGuarderia.changing) {
            controladorGuarderia.guarderiaChanged(jComboGuarderias);
        }
    }//GEN-LAST:event_jComboGuarderiasActionPerformed

    private void jComboGuarderias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderias1ActionPerformed
        if (comboBoxCreado && !controladorGuarderia.changing) {
            controladorGuarderia.guarderiaChanged(jComboGuarderias1);
        }
    }//GEN-LAST:event_jComboGuarderias1ActionPerformed

    private void jComboGuarderias2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderias2ActionPerformed
        if (comboBoxCreado && !controladorGuarderia.changing) {
            controladorGuarderia.guarderiaChanged(jComboGuarderias2);
        }
        
    }//GEN-LAST:event_jComboGuarderias2ActionPerformed

    private void jComboGuarderias3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderias3ActionPerformed
        if (comboBoxCreado && !controladorGuarderia.changing) {
            controladorGuarderia.guarderiaChanged(jComboGuarderias3);
        }
    }//GEN-LAST:event_jComboGuarderias3ActionPerformed

    private void jComboGuarderias4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderias4ActionPerformed
        if (comboBoxCreado && !controladorGuarderia.changing) {
            controladorGuarderia.guarderiaChanged(jComboGuarderias4);
        }
        controladorGuarderia.llenarRepresentantes(jComboGuarderias4, tablaRepresentantes);
    }//GEN-LAST:event_jComboGuarderias4ActionPerformed

    private void jComboGuarderias5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderias5ActionPerformed
        if (comboBoxCreado && !controladorGuarderia.changing) {
            controladorGuarderia.guarderiaChanged(jComboGuarderias5);
        }
    }//GEN-LAST:event_jComboGuarderias5ActionPerformed

    private void jComboGuarderias6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderias6ActionPerformed
        if (comboBoxCreado && !controladorGuarderia.changing) {
            controladorGuarderia.guarderiaChanged(jComboGuarderias6);
        }
    }//GEN-LAST:event_jComboGuarderias6ActionPerformed

    private void jComboGuarderias7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderias7ActionPerformed
        if (comboBoxCreado && !controladorGuarderia.changing) {
            controladorGuarderia.guarderiaChanged(jComboGuarderias7);
        }
    }//GEN-LAST:event_jComboGuarderias7ActionPerformed

    private void jComboGuarderias8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderias8ActionPerformed
        if (comboBoxCreado && !controladorGuarderia.changing) {
            controladorGuarderia.guarderiaChanged(jComboGuarderias8);
        }
    }//GEN-LAST:event_jComboGuarderias8ActionPerformed

    private void jComboGuarderias9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderias9ActionPerformed
        if (comboBoxCreado && !controladorGuarderia.changing) {
            controladorGuarderia.guarderiaChanged(jComboGuarderias9);
        }
    }//GEN-LAST:event_jComboGuarderias9ActionPerformed

    private void jComboGuarderias10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderias10ActionPerformed
        if (comboBoxCreado && !controladorGuarderia.changing) {
            controladorGuarderia.guarderiaChanged(jComboGuarderias10);
        }
    }//GEN-LAST:event_jComboGuarderias10ActionPerformed

    private void editGuarderiaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editGuarderiaButtonMouseClicked
        controladorGuarderia.editGuarderia();;
    }//GEN-LAST:event_editGuarderiaButtonMouseClicked

    private void editGuarderiaButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editGuarderiaButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editGuarderiaButton1MouseClicked

    private void addGuarderiaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addGuarderiaButtonMouseClicked
        controladorGuarderia.addGuarderia();
    }//GEN-LAST:event_addGuarderiaButtonMouseClicked

    private void jComboGuarderias11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGuarderias11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboGuarderias11ActionPerformed

    private void editGuarderiaButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editGuarderiaButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editGuarderiaButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addGuarderiaButton;
    public javax.swing.JButton addGuarderiaButton1;
    public javax.swing.JButton addGuarderiaButton2;
    private javax.swing.JButton buscarNinoButton;
    private javax.swing.JButton buscarNinoButton1;
    private javax.swing.JTextField buscarNinoTextField;
    private javax.swing.JTextField buscarNinoTextField1;
    public javax.swing.JLabel calleLabel;
    public javax.swing.JLabel calleLabel1;
    public javax.swing.JLabel calleLabel2;
    public javax.swing.JLabel casaLabel;
    public javax.swing.JLabel casaLabel1;
    public javax.swing.JLabel casaLabel2;
    public javax.swing.JLabel ciudadLabel1;
    public javax.swing.JLabel ciudadLabel2;
    public javax.swing.JLabel ciudadLabel3;
    public javax.swing.JButton deleteGuarderiaButton;
    public javax.swing.JButton deleteGuarderiaButton1;
    public javax.swing.JButton deleteGuarderiaButton2;
    public javax.swing.JButton editGuarderiaButton;
    public javax.swing.JButton editGuarderiaButton1;
    public javax.swing.JButton editGuarderiaButton2;
    public javax.swing.JLabel estadoLabel;
    public javax.swing.JLabel estadoLabel1;
    public javax.swing.JLabel estadoLabel2;
    public javax.swing.JLabel horaEntradaLabel;
    public javax.swing.JLabel horaEntradaLabel1;
    public javax.swing.JLabel horaEntradaLabel2;
    public javax.swing.JLabel horaSalidaLabel;
    public javax.swing.JLabel horaSalidaLabel1;
    public javax.swing.JLabel horaSalidaLabel2;
    public javax.swing.JComboBox<String> jComboGuarderias;
    public javax.swing.JComboBox<String> jComboGuarderias1;
    public javax.swing.JComboBox<String> jComboGuarderias10;
    public javax.swing.JComboBox<String> jComboGuarderias11;
    public javax.swing.JComboBox<String> jComboGuarderias2;
    public javax.swing.JComboBox<String> jComboGuarderias3;
    public javax.swing.JComboBox<String> jComboGuarderias4;
    public javax.swing.JComboBox<String> jComboGuarderias5;
    public javax.swing.JComboBox<String> jComboGuarderias6;
    public javax.swing.JComboBox<String> jComboGuarderias7;
    public javax.swing.JComboBox<String> jComboGuarderias8;
    public javax.swing.JComboBox<String> jComboGuarderias9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelActividades;
    private javax.swing.JPanel jPanelComida;
    private javax.swing.JPanel jPanelInfMedica;
    private javax.swing.JPanel jPanelInfoGuarderia;
    private javax.swing.JPanel jPanelInfoNino;
    private javax.swing.JPanel jPanelInfoNino1;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelInscripcion;
    private javax.swing.JPanel jPanelMultas;
    private javax.swing.JPanel jPanelNinos;
    private javax.swing.JPanel jPanelNinos1;
    private javax.swing.JPanel jPanelPagos;
    private javax.swing.JPanel jPanelPersonal;
    private javax.swing.JPanel jPanelRepresentantes;
    private javax.swing.JPanel jPanelTarifas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JLabel municipioLabel;
    public javax.swing.JLabel municipioLabel1;
    public javax.swing.JLabel municipioLabel2;
    public javax.swing.JLabel rifLabel;
    public javax.swing.JLabel rifLabel1;
    public javax.swing.JLabel rifLabel2;
    public javax.swing.JTable tablaRepresentantes;
    // End of variables declaration//GEN-END:variables
}
