/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AddInscripcionController;
import Controller.RepresentanteController;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fercon997
 */
public class JDAddInscripcion extends javax.swing.JDialog {
    AddInscripcionController controladorAG = new AddInscripcionController(this);
    InitialView parent;
    /**
     * Creates new form JDAgregarEmpleado
     */
    public JDAddInscripcion(InitialView parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Agregar Inscripcion");
        this.ciTxt.setEditable(false);
        this.letraNinoTxt.setEditable(false);
        controladorAG.llenarComboBoxGuarderias(guarderias);
        Agregar.setEnabled(false);
        ninoExistente.setEnabled(false);
        nuevoNino.setEnabled(false);
        //representanteExistente.setEnabled(false);
        //nuevoRepresentante.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ciTxt = new javax.swing.JTextField();
        letraNinoTxt = new javax.swing.JTextField();
        Agregar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        guarderias = new javax.swing.JComboBox<>();
        representanteExistente = new javax.swing.JButton();
        ninoExistente = new javax.swing.JButton();
        nuevoRepresentante = new javax.swing.JButton();
        nuevoNino = new javax.swing.JButton();
        Date date = new Date(0);
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        horaEntradaInscripcion = new javax.swing.JSpinner(sm);
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        Date date2 = new Date(0);
        SpinnerDateModel sm2 = new SpinnerDateModel(date2, null, null, Calendar.HOUR_OF_DAY);
        horaSalidaInscripcion = new javax.swing.JSpinner(sm2);
        Agregar1 = new javax.swing.JButton();
        Agregar2 = new javax.swing.JButton();
        Agregar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CI:");

        jLabel2.setText("Niño:");

        jLabel7.setText("Guardería");

        Agregar.setText("Agregar");
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMouseClicked(evt);
            }
        });
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        guarderias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guarderiasActionPerformed(evt);
            }
        });

        representanteExistente.setText("+");
        representanteExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                representanteExistenteActionPerformed(evt);
            }
        });

        ninoExistente.setText("+");
        ninoExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninoExistenteActionPerformed(evt);
            }
        });

        nuevoRepresentante.setText("Nuevo");
        nuevoRepresentante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoRepresentanteMouseClicked(evt);
            }
        });
        nuevoRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoRepresentanteActionPerformed(evt);
            }
        });

        nuevoNino.setText("Nuevo");
        nuevoNino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoNinoMouseClicked(evt);
            }
        });
        nuevoNino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoNinoActionPerformed(evt);
            }
        });

        JSpinner.DateEditor de = new JSpinner.DateEditor(horaEntradaInscripcion, "HH:mm");
        horaEntradaInscripcion.setEditor(de);
        DateFormat formatter = new SimpleDateFormat("HH:mm");
        try {
            java.util.Date horaEntrada = (java.util.Date) formatter.parse("00:00");
            horaEntradaInscripcion.setValue(horaEntrada);
        } catch (ParseException ex) {
            Logger.getLogger(JDAddInscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }

        jLabel62.setText("Hora de Entrada:");

        jLabel63.setText("Hora de Salida:");

        JSpinner.DateEditor de2 = new JSpinner.DateEditor(horaSalidaInscripcion, "HH:mm");
        horaSalidaInscripcion.setEditor(de2);
        try {
            java.util.Date horaSalida = (java.util.Date) formatter.parse("00:00");
            horaSalidaInscripcion.setValue(horaSalida);
        } catch (ParseException ex) {
            Logger.getLogger(JDAddInscripcion.class.getName()).log(Level.SEVERE, null, ex);
        }

        Agregar1.setText("Agregar Inf. Médica");
        Agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar1ActionPerformed(evt);
            }
        });

        Agregar2.setText("Agregar Actividades");
        Agregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar2ActionPerformed(evt);
            }
        });

        Agregar3.setText("Agregar Juegos");
        Agregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Agregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(guarderias, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel63)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel62)
                                            .addComponent(jLabel1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(horaEntradaInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(horaSalidaInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(ciTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                                    .addComponent(letraNinoTxt))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(ninoExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(nuevoNino, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(representanteExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(nuevoRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(Agregar3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Agregar1)
                                            .addComponent(Agregar2))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancelar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancelar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guarderias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ciTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(representanteExistente)
                    .addComponent(nuevoRepresentante))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(letraNinoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ninoExistente)
                    .addComponent(nuevoNino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(horaEntradaInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(horaSalidaInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Agregar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Agregar2)
                .addGap(4, 4, 4)
                .addComponent(Agregar3)
                .addGap(83, 83, 83)
                .addComponent(Agregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
         controladorAG.tablaClicked(tabla);// TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseClicked

    private void guarderiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guarderiasActionPerformed
        controladorAG.clearFields();
    }//GEN-LAST:event_guarderiasActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        
    }//GEN-LAST:event_AgregarActionPerformed

    private void representanteExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_representanteExistenteActionPerformed
        controladorAG.mostrarTabla(tabla, "representante");
    }//GEN-LAST:event_representanteExistenteActionPerformed

    private void ninoExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninoExistenteActionPerformed
        controladorAG.mostrarTabla(tabla, "nino");
    }//GEN-LAST:event_ninoExistenteActionPerformed

    private void nuevoRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoRepresentanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoRepresentanteActionPerformed

    private void nuevoNinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoNinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoNinoActionPerformed

    private void Agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregar1ActionPerformed

    private void Agregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregar2ActionPerformed

    private void Agregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregar3ActionPerformed

    private void AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseClicked
        controladorAG.agregarInscripcion();
    }//GEN-LAST:event_AgregarMouseClicked

    private void nuevoRepresentanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoRepresentanteMouseClicked
        controladorAG.agregarRepresentante();
    }//GEN-LAST:event_nuevoRepresentanteMouseClicked

    private void nuevoNinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoNinoMouseClicked
        this.dispose();
        parent.jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_nuevoNinoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Agregar;
    public javax.swing.JButton Agregar1;
    public javax.swing.JButton Agregar2;
    public javax.swing.JButton Agregar3;
    private javax.swing.JButton Cancelar;
    public javax.swing.JTextField ciTxt;
    public javax.swing.JComboBox<String> guarderias;
    public javax.swing.JSpinner horaEntradaInscripcion;
    public javax.swing.JSpinner horaSalidaInscripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField letraNinoTxt;
    public javax.swing.JButton ninoExistente;
    public javax.swing.JButton nuevoNino;
    public javax.swing.JButton nuevoRepresentante;
    public javax.swing.JButton representanteExistente;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
